# Generated by Django 5.0.6 on 2025-01-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0002_menu_remove_order_items_remove_order_reservation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=300)),
                ("image", models.ImageField(upload_to="image/")),
                ("price", models.IntegerField()),
                ("available", models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
