# Generated by Django 5.0.6 on 2025-01-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0004_cart_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoolDrinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="image/")),
                ("price", models.IntegerField()),
                ("available", models.BooleanField()),
            ],
        ),
    ]
