# Generated by Django 5.0.6 on 2025-01-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0005_cooldrinks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablereservation",
            name="table_number",
            field=models.CharField(
                choices=[
                    ("1", "Table 1"),
                    ("2", "Table 2"),
                    ("3", "Table 3"),
                    ("4", "Table 4"),
                ],
                max_length=10,
            ),
        ),
    ]
