# Generated by Django 5.0.6 on 2025-01-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0007_cartitem_cool_drink_alter_cartitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Hot Drinks", "Hot Drinks"),
                    ("Cool Drinks", "Cool Drinks"),
                    ("Snacks", "Snacks"),
                    ("Shakes", "Shakes"),
                ],
                default="Hot Drinks",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
