# Generated by Django 5.0.6 on 2025-01-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0008_remove_product_description_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="NiceDrink", max_length=300),
        ),
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="image/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
    ]
