# Generated by Django 5.0.6 on 2025-01-20 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0009_remove_product_category_product_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shakes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="image/")),
                ("price", models.IntegerField()),
                ("available", models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name="cartitem",
            name="Shakess",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cafe.shakes",
            ),
        ),
    ]
