# Generated by Django 5.0.6 on 2025-01-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafe", "0010_shakes_cartitem_shakess"),
    ]

    operations = [
        migrations.AddField(
            model_name="shakes",
            name="description",
            field=models.TextField(default="Drink The Shake"),
        ),
    ]
